---
# https://stackoverflow.com/questions/76898362/install-sdkman-on-ubuntu-server-through-ansible-playbook

- name: Playbook for installing Java using SDKMan
  hosts: all

  vars:
    - java_version: 21.0.1-zulu

  pre_tasks:
    - name: Installing SDKMAn dependencies
      become: true
      apt:
        state: latest
        name:
          - zip
          - unzip

  tasks:
    - name: Installing SDKMan
      become: no
      shell: "curl -s 'https://get.sdkman.io' | bash"
      args:
        executable: /bin/bash

    - name: Installing Java using SDKMan
      become: no
      shell: source ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ java_version }}
      args:
        executable: /bin/bash