---
version: '3.9'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: always
    privileged: true
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"