# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   defaultImage = "ubuntu/jammy64"

   servers = [
        {
          :hostname => "pc1",
          :box => defaultImage, 
          :ip => "192.168.56.50",
          :ssh_port => '2200'
        }
    ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.disk :disk, size: "40GB", primary: true

            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 4096]
                vb.customize ["modifyvm", :id, "--cpus", 2]
            end

	          #node.ssh.insert_key = false

            node.vm.provision "ansible" do |ansible|
                ansible.verbose = "v"
                ansible.playbook = "../../ansible/ubuntu-server-commons/master_playbook.yml"
            end
        end
    end
end
