---
- name: Playbook to install to enable automatic security updates
  hosts: all
  become: yes

  tasks:
    - name: Install the unattended-upgrades package (for automatic security updates)
      apt:
        name: unattended-upgrades
        state: present

    - name: Reconfigure unattended-upgrades to be sure they are installed
      command: "dpkg-reconfigure -f noninteractive -plow unattended-upgrades"

    - name: Enable the unattended-upgrades service
      systemd:
        name: unattended-upgrades
        enabled: yes
        state: started