---

- name: Playbook for updating and upgrading apt packages (Debian, Ubuntu)
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes