---
- name: Playbook for installing Docker and Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: Add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
          - docker-ce-cli
          - python3-pip
        update_cache: yes

    - name: Install Python Docker with pip (pip install docker)
      pip:
        name:
          - docker

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add current user to docker group
      user:
        name: vagrant
        groups: docker

    - name: Create the /etc/docker folder if doesn't exist
      command: "mkdir -p /etc/docker"

    - name: Set docker to use 127.0.0.1 as default for containers instead of the external machine address
      copy:
        content: |
          {
            "ip": "127.0.0.1"
          }
        dest: /etc/docker/daemon.json
        force: no