---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/iptables_module.html

- hosts: all
  become: yes
  tasks:
    - name: iptables IPV4 rules
      block:
        - name: Allow loopback traffic in INPUT chain
          iptables:
            chain: INPUT
            in_interface: lo
            jump: ACCEPT

        - name: Allow RELATED, ESTABLISHED traffic in INPUT chain
          iptables:
            chain: INPUT
            ctstate: ESTABLISHED,RELATED
            jump: ACCEPT

        - name: Allow SSH traffic in INPUT chain
          iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT

#        - name: Allow ICMP Echo Request traffic in INPUT chain
#          iptables:
#            chain: INPUT
#            protocol: icmp
#            icmp_type: echo-request
#            jump: ACCEPT

        - name: Allow loopback traffic in OUTPUT chain
          iptables:
            chain: OUTPUT
            out_interface: lo
            jump: ACCEPT

        - name: Allow RELATED, ESTABLISHED traffic in OUTPUT chain
          iptables:
            chain: OUTPUT
            ctstate: ESTABLISHED,RELATED
            jump: ACCEPT

        - name: Allow DNS (UDP port 53) traffic in OUTPUT chain
          iptables:
            chain: OUTPUT
            protocol: udp
            destination_port: 53
            jump: ACCEPT

        - name: Allow HTTP and HTTPS (TCP port 80, 443) traffic in OUTPUT chain
          iptables:
            chain: OUTPUT
            protocol: tcp
            ctstate: NEW
            destination_ports:
              - "80"
              - "443"
            jump: ACCEPT

        - name: Set default policy to DROP for INPUT chain
          iptables:
            chain: INPUT
            policy: DROP

        - name: Set default policy to DROP for FORWARD chain
          iptables:
            chain: FORWARD
            policy: DROP

        - name: Set default policy to DROP for OUTPUT chain
          iptables:
            chain: OUTPUT
            policy: DROP


    - name: iptables IPV6 rules
      block:
        - name: Allow loopback traffic in INPUT chain for IPv6
          iptables:
            chain: INPUT
            in_interface: lo
            jump: ACCEPT
            ip_version: ipv6

        - name: Allow RELATED, ESTABLISHED traffic in INPUT chain for IPv6
          iptables:
            chain: INPUT
            ctstate: ESTABLISHED,RELATED
            jump: ACCEPT
            ip_version: ipv6

        - name: Allow SSH traffic in INPUT chain for IPv6
          iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT
            ip_version: ipv6

#        - name: Allow ICMP traffic in INPUT chain for IPv6
#          iptables:
#            chain: INPUT
#            protocol: icmp
#            jump: ACCEPT
#            ip_version: ipv6

        - name: Allow loopback traffic in OUTPUT chain for IPv6
          iptables:
            chain: OUTPUT
            out_interface: lo
            jump: ACCEPT
            ip_version: ipv6

        - name: Allow RELATED, ESTABLISHED traffic in OUTPUT chain for IPv6
          iptables:
            chain: OUTPUT
            ctstate: ESTABLISHED,RELATED
            jump: ACCEPT
            ip_version: ipv6

        - name: Allow DNS (UDP port 53) traffic in OUTPUT chain for IPv6
          iptables:
            chain: OUTPUT
            protocol: udp
            destination_port: 53
            jump: ACCEPT
            ip_version: ipv6

        - name: Allow HTTP and HTTPS (TCP port 80, 443) traffic in OUTPUT chain
          iptables:
            chain: OUTPUT
            protocol: tcp
            ctstate: NEW
            destination_ports:
              - "80"
              - "443"
            jump: ACCEPT
            ip_version: ipv6

        - name: Set default policy to DROP for INPUT chain for IPv6
          iptables:
            chain: INPUT
            policy: DROP
            ip_version: ipv6

        - name: Set default policy to DROP for FORWARD chain for IPv6
          iptables:
            chain: FORWARD
            policy: DROP
            ip_version: ipv6

        - name: Set default policy to DROP for OUTPUT chain for IPv6
          iptables:
            chain: OUTPUT
            policy: DROP
            ip_version: ipv6
